name: Reclutamiento de agente

on: push

jobs: 
  reporte-de-reclutamiento:
    runs-on: ubuntu-latest
      

      steps:
        - name: El agente se presenta
          run: echo "Soy Lex Luthor y lider de la legion del mal"
          