name: Acceso a la fortaleza prohibida

on: 
  workflow_dispatch:

jobs:
  acceso-a-la-fortaleza:
    runs-on: ubuntu-latest

    steps:
      - name: El agente llega a la fortaleza
        run: |
          echo "Agente ${{ github.actor }} llega a la fortaleza"
          echo ""
          echo "Buscar los archivos de la Legion"
          ls -la
          echo ""
          echo "X pero que paso? no hay nada"

      - name: "Brainiac desbloquea la boveda"
        uses: actions/checkout@v4
        
      - name: 'Ahora si, vamos a ver los planes'
        run: |
          echo "Buscar los archivos de la Legion"
          ls -la
          echo "Funciona!!!"
          echo ""
          echo "Planes:"
          ls planes/
          echo "Villanos:"
          ls miembros/
          echo "Inteligencia:"
          ls inteligencia/perdedores