name: Acceso a la fortaleza prohibida

on: push

jobs:
  acceso-a-la-fortaleza:
    runs-on: ubuntu-latest

    steps:
      - name: El agente llega a la fortaleza
        run: |
          echo "Agente ${{ github.actor }} llega a la fortaleza"
          echo ""
          echo "Buscar los archivos de la Legion"
          ls -la
          echo ""
          echo "X pero que paso? no hay nada"