name: Comunicador de la legion

on:
  workflow_dispatch:
    inputs:
      villano:
        description: "Que villano envia el mensaje?"
        required: true
        type: choice
        options:
          - Lex Luthor
          - Brainiac
          - Darkseid
          - Joker
          - Bizarro
          - Mystique

      prioridad:
        description: "Nivel de prioridad"
        required: true
        type: choice
        options:
          - 🟢 Normal
          - 🟡 Alta
          - 🔴 Critica

      mensaje:
        description: "Mensaje para el consejo de la legion"
        required: true
        type: string
        default: "La mision fue un exito"

jobs:
  transmitir-mensaje:
    runs-on: ubuntu-latest

    steps:
      - name: "imprimir inputs"
        run: |
          echo "Inputs:"
          echo ""
          echo "Villano: ${{ github.villano }}"
          echo "Nivel de prioridad: ${{ github.prioridad }}"
          echo "Mensaje: ${{ github.mensaje }}"